### ISSUE TITLE
Restructure module in submodules

### ISSUE THREAD

**Issue by yakutovicha** [nanotech-empa/spmpy#10]
- [ ] #7  
- [ ]  #4

**Comment by bschuler** [comment]
Proposed structure:

- [ ] `__init__.py`
- [ ] `main.py`
- [ ] `referencing.py`
- [ ] `img_plotting.py`
- [ ] `img_processing.py`
- [ ] `img_export.py`
- [ ] `spec_plotting.py`
- [ ] `spec_processing.py`
- [ ] `spec fitting.py`
- [ ] `spec_export.py`
- [ ] `utils.py`
